language: python

python:
- 3.2
- 3.3
- 3.4
- 3.5
- 3.6
- 3.7

osx_image:
- xcode8.1
- xcode7.3
- xcode6.4

python:
- 3.6

install:
- make install

script:
- make chainsaw
- make minify
- make loader
